/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.github.wreulicke.logging;

import java.time.Duration;

import org.junit.jupiter.api.Test;

import io.micrometer.core.instrument.Timer;
import io.micrometer.core.instrument.simple.SimpleMeterRegistry;

public class AppTest {
	
	@Test
	public void test() {
		final SimpleMeterRegistry registry = new SimpleMeterRegistry();
		final Timer timer = Timer.builder("test.timer")
			.publishPercentiles(0.5, 0.95) // median and 95th percentile
			.publishPercentileHistogram()
			.minimumExpectedValue(Duration.ofMillis(1))
			.register(registry);
		final SomeService service = new SomeService(timer);
		service.doSomething();
	}
	
}
